<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Mediator.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Banking.Domain\Banking.Domain.csproj" />
    <ProjectReference Include="..\..\Characters\Characters.Application\Characters.Application.csproj" />
    <ProjectReference Include="..\..\Companies\Companies.Application\Companies.Application.csproj" />
    <ProjectReference Include="..\..\Shared\Shared.Integration.Abstractions\Shared.Integration.Abstractions.csproj" />
  </ItemGroup>

</Project>
