<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Mediator.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Characters.Domain\Characters.Domain.csproj" />
    <ProjectReference Include="..\..\Accounts\Accounts.Application\Accounts.Application.csproj" />
  </ItemGroup>

</Project>
