<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Mediator.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Companies.Domain\Companies.Domain.csproj" />
    <ProjectReference Include="..\..\Characters\Characters.Application\Characters.Application.csproj" />
  </ItemGroup>

</Project>
