<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Mediator.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shops.Domain\Shops.Domain.csproj" />
    <ProjectReference Include="..\..\Accounts\Accounts.Application\Accounts.Application.csproj" />
    <ProjectReference Include="..\..\Characters\Characters.Application\Characters.Application.csproj" />
    <ProjectReference Include="..\..\Companies\Companies.Application\Companies.Application.csproj" />
    <ProjectReference Include="..\..\Items\Items.Application\Items.Application.csproj" />
    <ProjectReference Include="..\..\Banking\Banking.Application\Banking.Application.csproj" />
    <ProjectReference Include="..\..\Shared\Shared.Integration.Abstractions\Shared.Integration.Abstractions.csproj" />
    <ProjectReference Include="..\..\World\World.Application\World.Application.csproj" />
  </ItemGroup>

</Project>
