<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Marten" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Companies.Application\Companies.Application.csproj" />
    <ProjectReference Include="..\..\Shared\Shared.Integration\Shared.Integration.csproj" />
    <ProjectReference Include="..\..\Shared\Shared.Infrastructure\Shared.Infrastructure.csproj" />
  </ItemGroup>

</Project>
